# Generated by Django 6.0.8 on 2026-09-25 08:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lugares', '0003_categoria_restaurante'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_visita', models.DateField(default=django.utils.timezone.localdate, verbose_name='data da visita')),
                ('nota', models.PositiveSmallIntegerField(blank=True, help_text='Em meias estrelas: 0 a 10 (7 = 3,5 estrelas).', null=True, validators=[django.core.validators.MaxValueValidator(10)])),
                ('critica', models.TextField(blank=True, verbose_name='crítica')),
                ('curtiu', models.BooleanField(default=False)),
                ('revisita', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='lugares.restaurante')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_visita', '-criado_em'],
                'indexes': [models.Index(fields=['restaurante', 'usuario', '-data_visita'], name='registro_rest_usuario_data')],
                'constraints': [models.CheckConstraint(condition=models.Q(('nota__isnull', True), ('nota__lte', 10), _connector='OR'), name='registro_nota_0_a_10')],
            },
        ),
    ]
