# Generated by Django 6.1.1 on 2026-09-27 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(help_text='Lado maior até 1.600 px.', upload_to='fotos/')),
                ('miniatura', models.ImageField(help_text='Lado maior até 480 px.', upload_to='fotos/')),
                ('largura', models.PositiveIntegerField()),
                ('altura', models.PositiveIntegerField()),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='registros.registro')),
            ],
            options={
                'verbose_name': 'foto',
                'ordering': ['criada_em', 'id'],
            },
        ),
    ]
