# Generated by Django 6.0.8 on 2026-09-25 08:22

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contas', '0001_initial'),
        ('lugares', '0003_categoria_restaurante'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.AddField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatares/'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='bio',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lugares.cidade'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nome_exibicao',
            field=models.CharField(blank=True, max_length=50, verbose_name='nome de exibição'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='termos_aceitos_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='termos_versao',
            field=models.CharField(blank=True, max_length=20, verbose_name='versão dos termos aceitos'),
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('username'), name='usuario_username_unico_ci'),
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='usuario_email_unico_ci'),
        ),
    ]
