/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/cadastro": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_cadastro_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/eu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auth_eu_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Sem CSRF de propósito: o pior que um site malicioso consegue é deslogar alguém. */
        post: operations["auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/senha/esqueci": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_senha_esqueci_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/senha/redefinir": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_senha_redefinir_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token/renovar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_token_renovar_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bairros": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["bairros_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categorias": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["categorias_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cidades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["cidades_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/eu/excluir": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST (e não DELETE) para que o corpo com a senha apareça no OpenAPI. */
        post: operations["eu_excluir_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/eu/perfil": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["eu_perfil_partial_update"];
        trace?: never;
    };
    "/api/v1/eu/senha": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["eu_senha_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/registros": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["registros_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/registros/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["registros_retrieve"];
        put?: never;
        post?: never;
        delete: operations["registros_destroy"];
        options?: never;
        head?: never;
        patch: operations["registros_partial_update"];
        trace?: never;
    };
    "/api/v1/restaurantes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["restaurantes_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/restaurantes/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["restaurantes_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/restaurantes/{slug}/registros": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["restaurantes_registros_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/usuarios/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["usuarios_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/usuarios/{username}/criticas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["usuarios_criticas_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/usuarios/{username}/diario": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["usuarios_diario_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Acesso: {
            acesso: string;
            renovacao?: string;
        };
        BarraHistograma: {
            /** Format: double */
            nota: number;
            quantidade: number;
        };
        CadastroRequest: {
            username: string;
            /** Format: email */
            email: string;
            senha: string;
            aceite_termos: boolean;
        };
        Categoria: {
            slug: string;
            nome: string;
        };
        CategoriaRequest: {
            slug: string;
            nome: string;
        };
        Cidade: {
            slug: string;
            nome: string;
            /** Estado (UF) */
            estado: string;
        };
        CidadeRequest: {
            slug: string;
            nome: string;
            /** Estado (UF) */
            estado: string;
        };
        ConfirmarSenhaRequest: {
            senha: string;
        };
        EsqueciSenhaRequest: {
            /** Format: email */
            email: string;
        };
        Eu: {
            /**
             * Usuário
             * @description Obrigatório. 150 caracteres ou menos. Letras, números e @/./+/-/_ apenas.
             */
            readonly username: string;
            /**
             * E-mail
             * Format: email
             */
            readonly email: string;
            /** Nome de exibição */
            readonly nome_exibicao: string;
            readonly bio: string;
            /** Format: uri */
            readonly avatar: string | null;
            readonly cidade: components["schemas"]["Cidade"] | null;
            /** Format: date-time */
            readonly membro_desde: string;
        };
        LoginRequest: {
            login: string;
            senha: string;
        };
        Mensagem: {
            mensagem: string;
        };
        MeuRegistro: {
            readonly id: number;
            /**
             * Data da visita
             * Format: date
             */
            data_visita: string;
            nota: number | null;
            curtiu: boolean;
        };
        Numeros: {
            visitados: number;
            visitados_este_ano: number;
        };
        PaginatedRegistroList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous: string | null;
            results: components["schemas"]["Registro"][];
        };
        PaginatedRestauranteResumoList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous: string | null;
            results: components["schemas"]["RestauranteResumo"][];
        };
        PatchedAtualizarPerfilRequest: {
            /** Nome de exibição */
            nome_exibicao?: string;
            bio?: string;
            cidade?: string | null;
            /** Format: binary */
            avatar?: string;
            remover_avatar?: boolean;
        };
        PatchedRegistroRequest: {
            restaurante_slug?: string;
            /**
             * Data da visita
             * Format: date
             */
            data_visita?: string;
            nota?: number | null;
            critica?: string;
            curtiu?: boolean;
            revisita?: boolean;
        };
        PerfilPublico: {
            /**
             * Usuário
             * @description Obrigatório. 150 caracteres ou menos. Letras, números e @/./+/-/_ apenas.
             */
            readonly username: string;
            /** Nome de exibição */
            readonly nome_exibicao: string;
            readonly bio: string;
            /** Format: uri */
            readonly avatar: string | null;
            readonly cidade: components["schemas"]["Cidade"] | null;
            /** Format: date-time */
            readonly membro_desde: string;
            readonly numeros: components["schemas"]["Numeros"];
        };
        RedefinirSenhaRequest: {
            uid: string;
            token: string;
            nova_senha: string;
        };
        Registro: {
            readonly id: number;
            readonly restaurante: components["schemas"]["RestauranteResumo"];
            readonly usuario: components["schemas"]["UsuarioResumo"];
            /**
             * Data da visita
             * Format: date
             */
            data_visita: string;
            nota: number | null;
            critica: string;
            curtiu: boolean;
            revisita: boolean;
            /** Format: date-time */
            readonly criado_em: string;
            /** Format: date-time */
            readonly atualizado_em: string;
        };
        RegistroRequest: {
            restaurante_slug: string;
            /**
             * Data da visita
             * Format: date
             */
            data_visita?: string;
            nota?: number | null;
            critica?: string;
            curtiu?: boolean;
            revisita?: boolean;
        };
        RenovacaoRequest: {
            /** @description Só para o app mobile. */
            renovacao?: string;
        };
        RestauranteDetalhe: {
            slug: string;
            nome: string;
            bairro: string;
            readonly cidade: components["schemas"]["Cidade"];
            readonly categorias: components["schemas"]["Categoria"][];
            /** Faixa de preço */
            faixa_preco: number | null;
            /** Format: double */
            readonly nota_media: number | null;
            total_avaliacoes: number;
            status: components["schemas"]["StatusEnum"];
            /** Endereço */
            endereco: string;
            /** Format: double */
            readonly latitude: number | null;
            /** Format: double */
            readonly longitude: number | null;
            readonly link_mapa: string;
            readonly histograma: components["schemas"]["BarraHistograma"][];
            readonly meu_ultimo_registro: components["schemas"]["MeuRegistro"] | null;
        };
        RestauranteResumo: {
            slug: string;
            nome: string;
            bairro: string;
            readonly cidade: components["schemas"]["Cidade"];
            readonly categorias: components["schemas"]["Categoria"][];
            /** Faixa de preço */
            faixa_preco: number | null;
            /** Format: double */
            readonly nota_media: number | null;
            total_avaliacoes: number;
            status: components["schemas"]["StatusEnum"];
        };
        RestauranteResumoRequest: {
            slug: string;
            nome: string;
            bairro?: string;
            /** Faixa de preço */
            faixa_preco?: number | null;
            total_avaliacoes?: number;
            status?: components["schemas"]["StatusEnum"];
        };
        /** @description Só para documentar a resposta de cadastro/login no OpenAPI. */
        Sessao: {
            usuario: components["schemas"]["Eu"];
            acesso: string;
            /** @description Só com `X-Cliente: mobile`. */
            renovacao?: string;
        };
        /**
         * @description * `ativo` - Ativo
         *     * `pendente` - Pendente
         *     * `fechado` - Fechado
         * @enum {string}
         */
        StatusEnum: "ativo" | "pendente" | "fechado";
        TrocarSenhaRequest: {
            senha_atual: string;
            nova_senha: string;
        };
        UsuarioResumo: {
            /**
             * Usuário
             * @description Obrigatório. 150 caracteres ou menos. Letras, números e @/./+/-/_ apenas.
             */
            readonly username: string;
            /** Nome de exibição */
            readonly nome_exibicao: string;
            /** Format: uri */
            readonly avatar: string | null;
        };
        Erro: {
            erro: {
                codigo: string;
                mensagem: string;
                campos: {
                    [key: string]: unknown;
                };
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_cadastro_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CadastroRequest"];
                "multipart/form-data": components["schemas"]["CadastroRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sessao"];
                };
            };
            /** @description Erro */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
        };
    };
    auth_eu_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Eu"];
                };
            };
            /** @description Erro */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
        };
    };
    auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
                "multipart/form-data": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sessao"];
                };
            };
            /** @description Erro */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
        };
    };
    auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RenovacaoRequest"];
                "multipart/form-data": components["schemas"]["RenovacaoRequest"];
            };
        };
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Erro */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
        };
    };
    auth_senha_esqueci_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EsqueciSenhaRequest"];
                "multipart/form-data": components["schemas"]["EsqueciSenhaRequest"];
            };
        };
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Mensagem"];
                };
            };
            /** @description Erro */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
        };
    };
    auth_senha_redefinir_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RedefinirSenhaRequest"];
                "multipart/form-data": components["schemas"]["RedefinirSenhaRequest"];
            };
        };
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Erro */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
        };
    };
    auth_token_renovar_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RenovacaoRequest"];
                "multipart/form-data": components["schemas"]["RenovacaoRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Acesso"];
                };
            };
            /** @description Erro */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
        };
    };
    bairros_list: {
        parameters: {
            query: {
                cidade: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Erro */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
        };
    };
    categorias_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Categoria"][];
                };
            };
            /** @description Erro */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
        };
    };
    cidades_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cidade"][];
                };
            };
            /** @description Erro */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
        };
    };
    eu_excluir_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmarSenhaRequest"];
                "multipart/form-data": components["schemas"]["ConfirmarSenhaRequest"];
            };
        };
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Erro */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
        };
    };
    eu_perfil_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedAtualizarPerfilRequest"];
                "multipart/form-data": components["schemas"]["PatchedAtualizarPerfilRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Eu"];
                };
            };
            /** @description Erro */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
        };
    };
    eu_senha_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrocarSenhaRequest"];
                "multipart/form-data": components["schemas"]["TrocarSenhaRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Acesso"];
                };
            };
            /** @description Erro */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
        };
    };
    registros_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistroRequest"];
                "multipart/form-data": components["schemas"]["RegistroRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Registro"];
                };
            };
            /** @description Erro */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
        };
    };
    registros_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Registro"];
                };
            };
            /** @description Erro */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
        };
    };
    registros_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Erro */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
        };
    };
    registros_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedRegistroRequest"];
                "multipart/form-data": components["schemas"]["PatchedRegistroRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Registro"];
                };
            };
            /** @description Erro */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
        };
    };
    restaurantes_list: {
        parameters: {
            query?: {
                bairro?: string;
                categoria?: string;
                cidade?: string;
                nota_min?: string;
                /**
                 * @description * `relevancia` - relevancia
                 *     * `nome` - nome
                 *     * `nota` - nota
                 *     * `populares` - populares
                 *     * `recentes` - recentes
                 */
                ordem?: "relevancia" | "nome" | "nota" | "populares" | "recentes";
                /** @description Um número de página dentro do conjunto de resultados paginado. */
                page?: number;
                preco?: number;
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedRestauranteResumoList"];
                };
            };
            /** @description Erro */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
        };
    };
    restaurantes_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestauranteDetalhe"];
                };
            };
            /** @description Erro */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
        };
    };
    restaurantes_registros_list: {
        parameters: {
            query?: {
                /** @description Um número de página dentro do conjunto de resultados paginado. */
                page?: number;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedRegistroList"];
                };
            };
            /** @description Erro */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
        };
    };
    usuarios_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerfilPublico"];
                };
            };
            /** @description Erro */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
        };
    };
    usuarios_criticas_list: {
        parameters: {
            query?: {
                /** @description Um número de página dentro do conjunto de resultados paginado. */
                page?: number;
            };
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedRegistroList"];
                };
            };
            /** @description Erro */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
        };
    };
    usuarios_diario_list: {
        parameters: {
            query?: {
                ano?: number;
                mes?: number;
                /** @description Um número de página dentro do conjunto de resultados paginado. */
                page?: number;
            };
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedRegistroList"];
                };
            };
            /** @description Erro */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
        };
    };
}
