# Generated by Django 6.1.1 on 2026-09-26 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lugares', '0004_extensao_unaccent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Desejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adicionado_em', models.DateTimeField(auto_now_add=True)),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desejos', to='lugares.restaurante')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desejos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-adicionado_em', '-id'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'restaurante'), name='desejo_unico_por_usuario')],
            },
        ),
    ]
