# Generated by Django 6.0.8 on 2026-09-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2, verbose_name='estado (UF)')),
                ('slug', models.SlugField(max_length=120, unique=True)),
            ],
            options={
                'ordering': ['nome'],
                'constraints': [models.UniqueConstraint(fields=('nome', 'estado'), name='cidade_nome_estado_unica')],
            },
        ),
    ]
