# Generated by Django 6.0.8 on 2026-09-25 07:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0002_semear_rio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fsq_id', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('nome_original', models.CharField(blank=True, max_length=120)),
                ('nome', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonte', models.CharField(blank=True, max_length=20)),
                ('id_externo', models.CharField(blank=True, max_length=64)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='endereço')),
                ('bairro', models.CharField(blank=True, db_index=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('faixa_preco', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='faixa de preço')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('pendente', 'Pendente'), ('fechado', 'Fechado')], db_index=True, default='ativo', max_length=10)),
                ('bloquear_importacao', models.BooleanField(default=False, help_text='Marque para que reimportações não sobrescrevam correções feitas à mão.')),
                ('nota_media', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('total_avaliacoes', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categorias', models.ManyToManyField(blank=True, related_name='restaurantes', to='lugares.categoria')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restaurantes', to='lugares.cidade')),
                ('sugerido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurantes_sugeridos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nome'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('id_externo', ''), _negated=True), fields=('fonte', 'id_externo'), name='restaurante_fonte_id_externo_unico'), models.CheckConstraint(condition=models.Q(('faixa_preco__isnull', True), models.Q(('faixa_preco__gte', 1), ('faixa_preco__lte', 4)), _connector='OR'), name='restaurante_faixa_preco_1_a_4')],
            },
        ),
    ]
